apiVersion: apps/v1

kind: Deployment

metadata:
  name: postgresql
  namespace: cern
  labels:
    app: postgresql
    tier: database

spec:

  selector:
    matchLabels:
      app: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgresql
        tier: database

    spec:
      containers:

        - name: k8s-db
          image: postgres:16-alpine
          
          env:

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_DATABASE

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_PASSWORD

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_USERNAME

          livenessProbe:
            exec:
              command:
                - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 30

          ports:
            - containerPort: 5432
              protocol: TCP

          resources:
            limits:
              memory: 512Mi
              cpu: "500m"
              
          volumeMounts:
            - name: postgresql-initdb
              mountPath: /docker-entrypoint-initdb.d/
      
            - name: postgres-pv-vol
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-pv-vol
          persistentVolumeClaim:
            claimName: postgres-pv-vol

        - name: postgresql-initdb
          configMap:
            name: postgresql-initdb-config
      
      restartPolicy: Always