apiVersion: v1

kind: PersistentVolume

metadata:
  name: postgres-pv-vol
  labels:
    type: local

spec:
  storageClassName: manual
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/"

---

apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: postgres-pv-vol
  labels:
    app: postgresql
    tier: database

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi