apiVersion: v1

kind: Secret

metadata:
  name: postgres-secret
  namespace: cern
  
type: Opaque

data:
  DB_DATABASE: Y2Vybl9yZXN0YXVyYW50IA== # cern_restaurant 
  DB_USERNAME: dGVjaF91c2Vy # tech_user
  DB_PASSWORD: cG9zdGdyZXM= # postgres
