apiVersion: v1

kind: Service

metadata:
  name: postgresql-svc
  namespace: cern
  labels:
    app: postgresql
    tier: database
spec:
  ports:
    - name: postgresql-svc
      port: 5432
      targetPort: 5432
  selector:
    app: postgresql
    tier: database