apiVersion: v1

kind: Service

metadata:
  name: frontend-svc
  namespace: cern
  labels:
    app: frontend
    tier: presentation
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: frontend
    tier: presentation