apiVersion: v1

kind: Service

metadata:
  name: backend-svc
  namespace: cern
  labels:
    app: backend
    tier: logical
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: backend
    tier: logical